### ISSUE TITLE
ETA on ads?

### ISSUE THREAD

**Issue by subsoap** [defold/extension-fbinstant#15]
Is there a debug problem with them?

Some ad related links

https://www.facebook.com/groups/instantgamedevelopers/permalink/768548260008002/

https://www.facebook.com/groups/instantgamedevelopers/permalink/768509343345227/

https://www.facebook.com/audiencenetwork/news-and-insights/rewarded-video-best-practices?hc_location=ufi

https://www.adcolony.com/blog/2016/08/12/rewarded-video-making-the-most-of-value-exchange/

**Comment by britzl** [comment]
I'll focus on this when the build server is back up again

**Comment by britzl** [comment]
I did some tests on mobile and I'm able to get an ad instance, but when I'm loading it I get an error since the game isn't live. I'm not sure if it's possible to test ads without having a game live?

These two are implemented. Rewarded video to come.

	fbinstant.load_interstitial_ad(placement, function(self, success)
		print("loaded interstitial", success)
		if not success then
			return
		end
		fbinstant.show_interstitial_ad(placement, function(self, success)
			print("showed interstitial", success)
		end)
	end)

**Comment by britzl** [comment]
I'm getting a {"code":"UNKNOWN","message":"(#606) Invalid placement_id"}"

**Comment by subsoap** [comment]
You need to setup stuff on the dashboard of the appid you are testing.

Dashboard -> Add a Product -> Audience Network click Setup

You'll need a business setup then select it

Then you create the name of the property or use one you already have

Then you can create a placement, you can create multiple, but it first has you choose either a rewarded video or an interstitial

Next you pick the payment account to associate with the property (you can reuse one you already created)

Then you can find the placement id somewhere like here

![2018-03-23 19_10_08-monetization manager - subsoap - ig test propety - first instant games ad space](https://user-images.githubusercontent.com/409170/37859217-d2515bfe-2ecd-11e8-99da-1b73b1334583.png)

Did you already follow these steps?

**Comment by britzl** [comment]
I didn't see the Copy ID button. That's probably it!

**Comment by subsoap** [comment]
At the end of the process above they give you a bundle id which is the wrong thing to use, I assume you used that the first time?

**Comment by britzl** [comment]
Got interstitial ads working now: https://github.com/defold/extension-fbinstant/releases/tag/3.2.0
Also added separate issue for rewarded video

**Comment by subsoap** [comment]
Are you testing on iOS or Android?

**Comment by subsoap** [comment]
```
03-25 17:25:53.872 I/chromium( 4787): [INFO:CONSOLE(299)] "INFO:ENGINE: Defold Engine 1.2.123 (46d8b7e)", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:25:54.020 I/chromium( 4787): [INFO:CONSOLE(299)] "INFO:ENGINE: Loading data from: dmanif:./game.dmanifest", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:25:54.197 I/chromium( 4787): [INFO:CONSOLE(299)] "INFO:ENGINE: Initialised sound device 'default'", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:25:54.198 I/chromium( 4787): [INFO:CONSOLE(299)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:25:54.686 I/chromium( 4787): [INFO:CONSOLE(299)] "ERROR:GAMESYS: Could not retrieve the physics socket '@physics': -6.", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:26:52.850 I/chromium( 4787): [INFO:CONSOLE(117)] "width: 1080 > ", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/index.html?psev=1 (117)
03-25 17:26:52.850 I/chromium( 4787): [INFO:CONSOLE(118)] "height:1917 > ", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/index.html?psev=1 (118)
03-25 17:26:52.905 I/chromium( 4787): [INFO:CONSOLE(68)] "Starting...", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/index.html?psev=1 (68)
03-25 17:26:54.233 I/chromium( 4787): [INFO:CONSOLE(301)] "Running...", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.234 I/chromium( 4787): [INFO:CONSOLE(301)] "Running...", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.234 I/chromium( 4787): [INFO:CONSOLE(301)] "Running...", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.235 I/chromium( 4787): [INFO:CONSOLE(301)] "Running...", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.235 I/chromium( 4787): [INFO:CONSOLE(301)] "Running...", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.236 I/chromium( 4787): [INFO:CONSOLE(301)] "Running...", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.317 I/chromium( 4787): [INFO:CONSOLE(301)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.317 I/chromium( 4787): [INFO:CONSOLE(301)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.317 I/chromium( 4787): [INFO:CONSOLE(301)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.317 I/chromium( 4787): [INFO:CONSOLE(301)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.317 I/chromium( 4787): [INFO:CONSOLE(301)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.318 I/chromium( 4787): [INFO:CONSOLE(301)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (301)
03-25 17:26:54.423 I/chromium( 4787): [INFO:CONSOLE(299)] "INFO:ENGINE: Defold Engine 1.2.123 (46d8b7e)", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:26:54.561 I/chromium( 4787): [INFO:CONSOLE(299)] "INFO:ENGINE: Loading data from: dmanif:./game.dmanifest", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:26:54.726 I/chromium( 4787): [INFO:CONSOLE(299)] "INFO:ENGINE: Initialised sound device 'default'", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:26:54.727 I/chromium( 4787): [INFO:CONSOLE(299)] "", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
03-25 17:26:55.206 I/chromium( 4787): [INFO:CONSOLE(299)] "ERROR:GAMESYS: Could not retrieve the physics socket '@physics': -6.", source: https://apps-220423735365494.apps.fbsbx.com/instant-bundle/1640583122697518/1514290622030078/dmloader.js (299)
```
Logcat output when testing XOXO example (and only changing placement id)

**Comment by britzl** [comment]
I'm testing on Android. Strange that you're not getting the callback...

**Comment by britzl** [comment]
Strange. It's working for me: 

03-26 06:23:16.180 14923 14923 I chromium: [INFO:CONSOLE(117)] "width: 1000 > ", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/index.html?psev=1 (117)
03-26 06:23:16.189 14923 14923 I chromium: [INFO:CONSOLE(118)] "height:1776 > ", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/index.html?psev=1 (118)
03-26 06:23:19.186 14923 14923 I chromium: [INFO:CONSOLE(301)] "Running...", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (301)
03-26 06:23:19.359 14923 14923 I chromium: [INFO:CONSOLE(301)] "", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (301)
03-26 06:23:21.133 14923 14923 I chromium: [INFO:CONSOLE(68)] "Starting...", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/index.html?psev=1 (68)
03-26 06:23:21.437 14923 14923 I chromium: [INFO:CONSOLE(299)] "INFO:ENGINE: Defold Engine 1.2.123 (46d8b7e)", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (299)
03-26 06:23:21.813 14923 14923 I chromium: [INFO:CONSOLE(299)] "INFO:ENGINE: Loading data from: dmanif:./game.dmanifest", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (299)
03-26 06:23:22.218 14923 14923 I chromium: [INFO:CONSOLE(299)] "INFO:ENGINE: Initialised sound device 'default'", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (299)
03-26 06:23:22.218 14923 14923 I chromium: [INFO:CONSOLE(299)] "", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (299)
03-26 06:23:23.286 14923 14923 I chromium: [INFO:CONSOLE(299)] "ERROR:GAMESYS: Could not retrieve the physics socket '@physics': -6.", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (299)
03-26 06:23:26.974 14923 14923 I chromium: [INFO:CONSOLE(1)] "Ads.insert()", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/XOXO.js (1)
03-26 06:23:26.975 14923 14923 I chromium: [INFO:CONSOLE(1)] "Ads.insert() 130801227620858_156771488357165 [object Object]", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/XOXO.js (1)
03-26 06:23:26.975 14923 14923 I chromium: [INFO:CONSOLE(1)] "Ads.insert() done", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/XOXO.js (1)
03-26 06:23:26.978 14923 14923 I chromium: [INFO:CONSOLE(299)] "DEBUG:SCRIPT: loaded interstitial	true", source: https://apps-130801227620858.apps.fbsbx.com/instant-bundle/1638472049550256/1649283928519656/dmloader.js (299)

**Comment by subsoap** [comment]
Maybe add me to the app you are testing so I can test it on my device to rule other things out?

**Comment by britzl** [comment]
Added!

**Comment by subsoap** [comment]
Ads worked so might be something in the setup of the app itself on the Facebook side. I'll investigate.

**Comment by subsoap** [comment]
![2018-03-25 21_58_53-xoxo - dashboard - facebook for developers](https://user-images.githubusercontent.com/409170/37887651-d709ea2a-3077-11e8-98b7-e58c398a6e92.png)
![2018-03-25 21_59_39-open](https://user-images.githubusercontent.com/409170/37887652-d7204ab8-3077-11e8-9874-af47fa1d2396.png)

Here's a difference, did you already put your Audience Network for review for the XOXO app? I have not yet for appid I am testing, will do that now...

**Comment by subsoap** [comment]
By the way, this version of the XOXO on Android also goes from 0 to instantly 100% loaded too on this decide. Does it show actual progress while loading for you on Android?

**Comment by britzl** [comment]
Nope, nothing has been put for review. But now that you mention it the app was whitelisted by FB. Although that was before the SDK and ads was announced and made available for all devs. Still, it could have significance.

And yes, the progress goes to 100 immediately for me as well. I haven't had time to investigate why though.

**Comment by subsoap** [comment]
I'll see if the review goes if it changes. The documentation didn't seem to imply you had to put the Audience Network into review for testing but that may be different for Instant Games vs native apps using Audience Network.

**Comment by subsoap** [comment]
I'll test on another appid soon too.

**Comment by subsoap** [comment]
![2018-03-26 10_08_25](https://user-images.githubusercontent.com/409170/37921375-8517df62-30de-11e8-83c1-6532cd629c7a.png)

This appid now has a green checkmark (someone on facebook instant group said it shows up a few hours after first trying to test ads??)

I'm not sure if ads are working now as they are not showing up yet but also not in XOXO which was working yesterday. Will test again in a few hoursish.

**Comment by subsoap** [comment]
I got an ad on XOXO but not on other yet. When an ad doesn't show up in XOXO it doesn't show any of the callback prints either.

**Comment by subsoap** [comment]
Closing since they work and it not working before was probably Facebook.
