### ISSUE TITLE
fbinstant.get_player_stats() should get multiple stats

### ISSUE THREAD

**Issue by AGulev** [defold/extension-fbinstant#2]
is fbinstant.get_player_stats()  work only with one value per time?

Original example is:
```
FBInstant.player
  .getStatsAsync(['level', 'zombiesSlain'])
  .then(function(stats)) {
    console.log('stats are loaded');
    var level = data['level'];
    var zombiesSlain = data['zombiesSlain'];
  });
```

**Comment by britzl** [comment]
Good point. It currently expects a single string key, ie you can only get one stat per call. I'll change this to accept a JSON encoded array of keys.

**Comment by AGulev** [comment]
@britzl it works like a charm!

**Comment by britzl** [comment]
https://github.com/defold/extension-fbinstant/releases/tag/2.0.0
