### ISSUE TITLE
Bug in the xoxo example

### ISSUE THREAD

**Issue by subsoap** [defold/extension-fbinstant#20]
If board is full it will say it's a draw even though there was a winner.

![bug](https://user-images.githubusercontent.com/409170/37761127-0a6f9338-2d76-11e8-833f-ffbd800823cc.png)

**Comment by subsoap** [comment]
It's not that the board is full, it's just that the game doesn't detect 3 across only 3 down, I'll submit a fix.

**Comment by britzl** [comment]
https://github.com/defold/extension-fbinstant/releases/tag/3.3.0
