### ISSUE TITLE
Android loads from 0 to 100% instantly instead of showing progress

### ISSUE THREAD

**Issue by subsoap** [defold/extension-fbinstant#26]
Also happens in Chrome so may be easier to debug there.

Other non-Defold based games on Android show loading progress. Loading progress of Defold based games does work on iOS.

**Comment by AGulev** [comment]
I am not sure that I understand where is the bug.
How it looks like for me on android:
https://youtu.be/xcCja9jQn6c

**Comment by subsoap** [comment]
What Android version are you testing on?

I tested on 7.0 @britzl was able to reproduce it

**Comment by AGulev** [comment]
Android 6.0 Xiaomi redmi note4
Can you try using this link: https://www.facebook.com/instantgames/285409181956230/ ?

**Comment by subsoap** [comment]
That seems to load properly on Chrome and Android so it must be something different you are doing vs the template html included in the fbinstant extension. Could you check the fbinstant extension bundled version and see where the error is compared to your version?

**Comment by subsoap** [comment]
I'm checking this now too.

**Comment by subsoap** [comment]
Could you post your .html template?

**Comment by subsoap** [comment]
You should test the XOXO example on your phone too to see if it loads properly or not like your card game does.

**Comment by AGulev** [comment]
yes, of course.
I made my own template (didn't use xoxo template)
For example in my template I use early FBInstant init.

[engine_template.html.zip](https://github.com/defold/extension-fbinstant/files/1855152/engine_template.html.zip)

**Comment by AGulev** [comment]
Yes, xoxo game loads 0-100% instantly

**Comment by subsoap** [comment]
I tested your template and it seemed to make loading work, so need to find what's wrong with the fbinstant extension built in html to make it not work on Android (it works on iOS)

**Comment by AGulev** [comment]
Maybe the reason is early initialization of SDK ?
FBInstant.initializeAsync().then(function() {...})

**Comment by subsoap** [comment]
I'll test that

**Comment by subsoap** [comment]
Seems like it could be that, doing more testing.

**Comment by AGulev** [comment]
This is one of the Best Practice recommendation :
**Load resources in parallel with initializeAsync**
https://developers.facebook.com/docs/games/instant-games/best-practices

I save is init variable when loading into Module._instant_inited
```
FBInstant.initializeAsync().then(function() {
        Module._instant_inited = 1;
})
```

 Then checking is_init in lua:

```
function M.init(callback)
  if tonumber(html5.run("Module._instant_inited")) == 1 then
    callback()
  else
    fbinstant.initialize(function(self, success)
      callback()
    end)
  end
end
```

**Comment by subsoap** [comment]
I tested the change and it worked on Chrome and Android for me.
So template html should be changed likewise in some way @britzl 

```

        app_container.style.width = width+"px";
        app_container.style.height = height+"px";

        game_canvas.width = width*dpi;
        game_canvas.height = height*dpi;

        window.console.log("width: " + game_canvas.width + " > "+ game_canvas.style.width)
        window.console.log("height:" + game_canvas.height + " > "+ game_canvas.style.height)
    }
	
  FBInstant.initializeAsync().then(function() {
	Module._instant_inited = 1;

  });	

    resize_game_canvas();

    window.addEventListener('resize', resize_game_canvas, false);
    window.addEventListener('orientationchange', resize_game_canvas, false);

    </script>
```

**Comment by subsoap** [comment]
@britzl I did some more tests for this, I'll submit a pr soon with changes to the api tester and xoxo example.

**Comment by britzl** [comment]
Released: https://github.com/defold/extension-fbinstant/releases/tag/3.6.0
