### ISSUE TITLE
String allocations are not free'd

### ISSUE THREAD

**Issue by AGulev** [defold/extension-fbinstant#3]
you make a lot of allocations on js side, but never free() the memomry after push to lua.

**Comment by britzl** [comment]
I've done a lot of changes to the string handling on the js side. Would you mind trying out this branch: https://github.com/defold/extension-fbinstant/tree/free

I've done tests on two different apps and things work as expected. Still, would be nice with an additional test.

**Comment by AGulev** [comment]
no problem, I'll tet it asap.

**Comment by AGulev** [comment]
I test in my game - it works.
I am using not a lot of api methods, but methods that I am use working fine.

**Comment by britzl** [comment]
https://github.com/defold/extension-fbinstant/releases/tag/1.0.0
