### ISSUE TITLE
Improve how supported APIs can be checked

### ISSUE THREAD

**Issue by britzl** [defold/extension-fbinstant#33]
Returning a set makes it easier to check if a certain function is supported or not:

```
local supported_apis = fbinstant.get_supported_apis()
if supported_apis["getInterstitialAdAsync"] then
   -- load/show interstitial
end
```

Or maybe even utility functions such as fbinstant.is_ads_supported() would be event better?

**Comment by subsoap** [comment]
Both would be good. Easy helper functions for specific API features that are unique to some platforms like ads, and to be able to check in a cleaner way any API feature.
