### ISSUE TITLE
Need to change example from now no longer working activity stores into using web server (heroku) based cloud save for context data

### ISSUE THREAD

**Issue by subsoap** [defold/extension-fbinstant#40]
Defold example is currently broken as activity store api has been disabled

---

Example here

https://origincache.facebook.com/developers/resources/?id=tic-tac-toe.zip

I can help make changes / set it up later

**Comment by britzl** [comment]
I used the Heroku backend before the Activity Store API was available. I'll dig that up and see if I have to do any changes.

**Comment by britzl** [comment]
In progress. The backend implementation has changed a bit.

**Comment by britzl** [comment]
Released in 3.7.0
