### ISSUE TITLE
Mock doesn't contain rewarded video mock functions

### ISSUE THREAD

**Issue by Teshla** [defold/extension-fbinstant#45]
Mock lacks some supported api functions: Discovered so far are load_rewarded_video and show_rewarded_video

**Comment by subsoap** [comment]
https://github.com/defold/extension-fbinstant/blob/master/tictactoe/start/start.gui_script

**Comment by britzl** [comment]
Added: https://github.com/defold/extension-fbinstant/releases/tag/3.8.0
