### ISSUE TITLE
Add In-app purchase support

### ISSUE THREAD

**Issue by britzl** [defold/extension-fbinstant#46]
https://developers.facebook.com/blog/post/2018/05/01/in-app-purchases-instant-game-platform/
https://developers.facebook.com/docs/games/instant-games/guides/in-app-purchases

**Comment by anko91** [comment]
Hello! We really need this functionality, we are faced with the situation that we can not release the project without it. Can you please tell me when we can expect this feature?

**Comment by britzl** [comment]
We can focus on this functionality during the week starting on Monday the 16th. If all goes well the IAP support can be shipped by the end of that week. Perhaps sooner depending on progress of Leaderboard implementation.

**Comment by britzl** [comment]
Fixed in 3.10.0 (https://github.com/defold/extension-fbinstant/releases/tag/3.10.0)
