### ISSUE TITLE
Loading rewarded video throws CLIENT_UNSUPPORTED_OPERATION

### ISSUE THREAD

**Issue by koorva** [defold/extension-fbinstant#54]
Rewarded video does not loading. Request throws:
**code: "CLIENT_UNSUPPORTED_OPERATION"
message: "Client does not support the message: getrewardedvideoasync"**

**Comment by britzl** [comment]
Are you testing this on mobile?

**Comment by koorva** [comment]
Yes. Nothing happens. Loading request returns false

**Comment by koorva** [comment]
get_purchases also return null. But i have iap products on Facebook

**Comment by britzl** [comment]
I recall that there were quite a few things I needed to setup before I could get both IAP and ads to work. Have you signed up for Audience Network? Do you have a Payment Account set up?

**Comment by koorva** [comment]
Yes. Yes. Do we need to review our app for test ads and IAP?

**Comment by britzl** [comment]
Ok, so for IAP:

What does fbinstant.on_payments_ready() return?
And fbinstant.get_product_catalog(callback)?
Have you followed these steps: https://developers.facebook.com/docs/games/instant-games/guides/in-app-purchases ?

For ads:
Where do you see the "CLIENT_UNSUPPORTED_OPERATION"? In the console? When calling fbinstant.load_rewarded_video(placement, callback)?

**Comment by britzl** [comment]
Ok, good to hear that rewarded videos work!

For IAP it's probably some setting that is missing somewhere for your project. This is how it looks in the example project where IAP purchases are working:

![screen shot 2018-11-21 at 23 10 09](https://user-images.githubusercontent.com/1300688/48870904-d6fb8600-ede2-11e8-9071-c9e0e08eff4f.png)

**Comment by koorva** [comment]
Good news: administrators can see IAPs. Bad news developers can`t. I don`t know why.

**Comment by britzl** [comment]
Ok, hmm, that might be something to ask Facebook about. You should ask this in the Instant Games group on Facebook.

**Comment by britzl** [comment]
Closing. Rewarded video was confirmed to work.
