### ISSUE TITLE
choose_context fails if optional "options" parameter is omitted

### ISSUE THREAD

**Issue by totebo** [defold/extension-fbinstant#60]
This fails:
`fbinstant.choose_context(nil, callback)`

This works:
`fbinstant.choose_context("{}", callback)`

**Comment by britzl** [comment]
Thanks. Will take a look straight away!

**Comment by britzl** [comment]
This will work: fbinstant.choose_context(callback)

The readme specifies:

`fbinstant.choose_context([options,] callback)`

Which means that you can omit the options argument completely. I should probably add support for it being nil as well though...

**Comment by totebo** [comment]
Oh, I have never seen *completely* optional parameters before, nice one!
