### ISSUE TITLE
fbinstant.set_leaderboard_score fails silently

### ISSUE THREAD

**Issue by totebo** [defold/extension-fbinstant#62]
Too many leaderboard requests can produce an error like this, causing the callback to never fire:

`FBInstant_PlatformSetLeaderboardScoreAsync - error: Game called too many leaderboard APIs too quickly. Reduce the rate of requests in order to avoid being rate-limited.`

**Comment by britzl** [comment]
Hmm, are you still having a problem with this? You really should be getting a callback with values set to 0 or nil.

**Comment by totebo** [comment]
Haven't tested recently, maybe FB have changed/fixed something?

**Comment by britzl** [comment]
I did some changes right around the time that you created this issue and I believe the fix has solved your problem. If you are able to try to reproduce the problem again I'd be very grateful.

**Comment by totebo** [comment]
Will do when I get some time to spare! Although if you say it might be
fixed, I have a hunch it IS fixed. :)

**Comment by britzl** [comment]
Closing. It should be fixed. Reopen if this isn't the case.
