### ISSUE TITLE
Add support for matchPlayerAsync( )

### ISSUE THREAD

**Issue by britzl** [defold/extension-fbinstant#71]
And checkCanPlayerMatchAsync( )

**Comment by gustavobussolotti** [comment]
have any position of this feature? Thanks.

**Comment by totebo** [comment]
Would also like to know if this is scheduled to be implemented?

**Comment by britzl** [comment]
Fixed in https://github.com/defold/extension-fbinstant/releases/tag/5.4.0

**Comment by gustavobussolotti** [comment]
Thanks
