### ISSUE TITLE
fbinstant.log_event() fails if optional value(s) are omitted

### ISSUE THREAD

**Issue by totebo** [defold/extension-fbinstant#76]
If "value_to_sum" or "parameters" are omitted the operation fails.

These parameters are optional in the JavaScript version of the API:
https://developers.facebook.com/docs/games/instant-games/sdk/fbinstant6.0

**Comment by britzl** [comment]
Here's a PR that handles if value_to_sum is nil: https://github.com/defold/extension-fbinstant/pull/78

Please give it a try and let me know if it works as expected!

**Comment by totebo** [comment]
Both `valueToSum` and `parameters` can be omitted in the Facebook API. It looks like 0 is sent if valueToSum is nil now? Would be good to just be able to go:

`fbinstant.log_event( "Kick" )`

And the only thing sent is the "Kick" event id?

**Comment by totebo** [comment]
Back on this, and can confirm it still fails if value_to_sum is omitted:

```
local event_name = "test"
local value_to_sum = nil
local all_parameters_json = {test=1}
fbinstant.log_event(event_name, value_to_sum, all_parameters_json)
```

**Comment by britzl** [comment]
I've added a check if value_to_sum is a number or not. Anything other than a number will be treated as 0. Would you mind testing this branch:

https://github.com/defold/extension-fbinstant/archive/dev-valuetosum_nil.zip

**Comment by totebo** [comment]
All of the examples above now work. Great job, thanks!
