### ISSUE TITLE
The callback for fbinstant.share() doesn't trigger "when the share dialog has been closed"

### ISSUE THREAD

**Issue by totebo** [defold/extension-fbinstant#77]
It triggers "success=true" when the share dialog has been opened. This means there is no way of knowing if the user shared or cancelled the share dialogue.

**Comment by britzl** [comment]
It doesn't look like the Javscript SDK for fbinstant.shareAsync() indicates success either:

https://developers.facebook.com/docs/games/instant-games/sdk/fbinstant6.3

The success = true simply indicates creation of the share dialog was successful or not (ie if the args were ok etc). Not if the user actually shared or cancelled.

**Comment by totebo** [comment]
Yeah, some strange documentation there. The Facebook docs are wrong:

"the returned promise will resolve when the dialog is closed"

It is resolved after it's been opened (or failed to open). 

This one can probably be closed.

**Comment by britzl** [comment]
Ok, closing
