### ISSUE TITLE
Add FBInstant.getLeaderboardAsync( )

### ISSUE THREAD

**Issue by britzl** [defold/extension-fbinstant#8]
And all operations on the leaderboards themselves: https://developers.facebook.com/docs/games/instant-games/sdk/fbinstant6.0#leaderboard

**Comment by anko91** [comment]
Hello! We really need this functionality, we are faced with the situation that we can not release the project without it. Can you please tell me when we can expect this feature?

**Comment by britzl** [comment]
I can ship the Leaderboard functionality during the week starting on Monday
the 9th.

**Comment by britzl** [comment]
I can ship this functionality during the week starting on Monday the 9th.

**Comment by britzl** [comment]
FYI: Work is now in progress. Likely to be completed tomorrow.
