### ISSUE TITLE
Send screenshot/image with the context update

### ISSUE THREAD

**Issue by britzl** [defold/extension-fbinstant#9]
The payload passed to fbinstant.update() must include an image. This is typically a screenshot or some other visuals that show the current progress of the game.

Add a function to properly base64 encode and format the `image` value.

Look into Canvas.toDataURL and also dig into the Defold-Screenshot extension on HTML5.

Blank/empty image:

"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAADElEQVQImWNgoBMAAABpAAFEI8ARAAAAAElFTkSuQmCC"

**Comment by totebo** [comment]
I'm implementing context update and sharing in my game at the moment. I'd be able to test this if needed.

**Comment by britzl** [comment]
The defold-screenshot extension now has support for HTML5 screenshots:

https://github.com/britzl/defold-screenshot
